### PR TITLE
Get Summary of e2e tests from command output

### PR DESCRIPTION
**Pull request by Poorna-Gottimukkula1**

### CODE REVIEW

**Comment by yussufsh** [comment]
@Poorna-Gottimukkula1 please sign your commit. Click on the details link against the DCO check for more information.

**Review by yussufsh — APPROVED** [review]
/approve
/hold
...for DCO

**Comment by Poorna-Gottimukkula1** [comment]
> @Poorna-Gottimukkula1 please sign your commit. Click on the details link against the DCO check for more information.

@yussufsh I have signed the commit, Thx!

**Review by pravin-dsilva — APPROVED** [review]

**Pull request merged**
