### PR TITLE
tmp fix added for 4.15 e2e

### PR DESCRIPTION
**Pull request by Poorna-Gottimukkula1**

### CODE REVIEW

**Comment by yussufsh** [comment]
More details on why the fix is needed will be helpful.
We should create an issue before and then raise a pull request to mark the issue.

**Comment by Poorna-Gottimukkula1** [comment]
Created a issue https://github.com/ocp-power-automation/ocp4-playbooks-extras/issues/64 with the details

**Review by yussufsh — APPROVED** [review]
/lgtm

**Pull request merged**
