### PR TITLE
Create OWNERS

### PR DESCRIPTION
**Pull request by yussufsh**
Signed-off-by: Yussuf Shaikh <yussuf.shaikh1@ibm.com>

### CODE REVIEW

**Review by pravin-dsilva — APPROVED** [review]
/lgtm

**Comment by mkumatag** [comment]
> /meow

For this to work, we need to have a prow webhook registered in the gh repo settings.

cc @Rajalakshmi-Girish can you please help these folks to configure the webhook?

**Comment by yussufsh** [comment]
Thanks @mkumatag @Rajalakshmi-Girish 👍

**Pull request merged**
